force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy CCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell CCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tradesDataTableController_TEST.cls
@isTest
private class  tradesDataTableController_TEST {
    @TestSetup 
    static void testSetup(){
            List < Trade__c > tradesToInsert = new list < Trade__c > ();
    		Trade__c trade = new Trade__c();
    		trade.Sell_Currency__c = 'EUR';
    		trade.Buy_Currency__c = 'GBP';
    		trade.Rate__c = 123.45;
    		trade.Sell_Amount__c = 12213;
    		tradesToInsert.add(trade);
    		insert tradesToInsert;
    }
    @isTest
    private static void getTradesTest() {
        List < Trade__c > trades = tradesDataTableController.getTrades();
        System.assert(!trades.isempty(), 'Expected trades were retrieved');
    }

    @isTest
    private static void createTrade() {
        tradesDataTableController.JSONData jsonInfo = new tradesDataTableController.JSONData();
        jsonInfo.initalRate = 'EUR';
        jsonInfo.finaleRate = 'GBP';
        jsonInfo.sellAmount = 12213;
        jsonInfo.rate = 123.45;
        Map < String, Object > result = tradesDataTableController.createTrade(json.serialize(jsonInfo));
        System.assert(result.get('result')=='OK', 'Expected trades were created');
    }
}