force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount_Form__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount_Form__c</fullName>
    <formula>Sell_Amount__c * Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy CCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell CCY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tradesDataTableController.cls
public with sharing class tradesDataTableController {
    public static JSONData data;

     @AuraEnabled(cacheable = true)
     public static List < Trade__c > getTrades() {
    	List < Trade__c > trades = new List < Trade__c > ();
    	try {
    		trades = [SELECT Id, Name, Buy_Amount_Form__c, Buy_Currency__c, Date_Booked__c, Rate__c, Sell_Amount__c, Sell_Currency__c FROM Trade__c order by Date_Booked__c Desc];
    	} catch (Exception e) {
    		system.debug('tradesDataTableController -- getTrades --> Exception Type: ' + e.getTypeName() + ' Exception Message: ' + e.getMessage());
    		system.debug('tradesDataTableController -- getTrades --> Exception Line: ' + e.getLineNumber() + ' Exception StackTrace: ' + e.getStackTraceString());
    	}
    	return trades;
    }

     @AuraEnabled
     public static Map < String, Object > createTrade(String JsonInfo) {
    	Map < String, Object > returnMap = new Map < String, Object > ();
    	try {
            system.debug('tradesDataTableController --> JsonInfo' + JsonInfo);
    		data = (JSONData) JSON.deserializeStrict(JsonInfo, JSONData.class);
            system.debug('tradesDataTableController --> JsonInfo Des' + data);
    		List < Trade__c > tradesToInsert = new list < Trade__c > ();
    		Trade__c trade = new Trade__c();
    		trade.Sell_Currency__c = data.initalRate;
    		trade.Buy_Currency__c = data.finaleRate;
    		trade.Rate__c = data.rate;
    		trade.Sell_Amount__c = data.sellAmount;
    		tradesToInsert.add(trade);
    		insert tradesToInsert;

    	} catch (Exception e) {
    		returnMap.put('result', 'KO');
    		returnMap.put('error', e.getMessage());
    		//String logResponse = e.getMessage();
    		//String logRequest = JSON.serialize(i);
    		//APU003_WriteEAILog.writeLog(logRequest,logResponse,'Outbound', 'Sincrona', true, SYSTEMS, true, o.Id );
    		system.debug('tradesDataTableController -- createTrade --> Exception Type: ' + e.getTypeName() + ' Exception Message: ' + e.getMessage());
    		system.debug('tradesDataTableController -- createTrade --> Exception Line: ' + e.getLineNumber() + ' Exception StackTrace: ' + e.getStackTraceString());
    		return returnMap;
    	}
    	returnMap.put('result', 'OK');
    	return returnMap;

    }

    public class JSONData {
        public String initalRate { get; set; }
        public String finaleRate { get; set; }
        public Decimal sellAmount { get; set; }
        public Decimal rate { get; set; }
        public JSONData (){}
    }
}